export { QuestionPool, globalPool }              from './questionPool';
export { computeDifficulty, recommendedTier, SPEED_BONUS_PTS, SPEED_BONUS_SECS } from './difficultyAdapter';
export type { DifficultyContext, DifficultyProfile, DifficultyLabel }            from './difficultyAdapter';
export { validateAnswer, summarizeRound }        from './answerValidator';
export type { ValidationInput, ValidationResult }                                from './answerValidator';
export { CategoryDraftManager, randomCategories } from './categoryDraft';
export type { DraftState, DraftMode, DraftPick }                                from './categoryDraft';
export { RoundManager }                          from './roundManager';
export type { TurnInfo, RoundInfo }                                             from './roundManager';
export { GameStateMachine, gameFSM, ENGINE_TO_STORE_PHASE } from './stateMachine';
export type { EnginePhase, PhaseEvent }                                         from './stateMachine';
export { QuestionEngine, engine }                from './questionEngine';
export type { EngineSnapshot, BoardBuilderOptions }                             from './questionEngine';
export { SabotageEngine, sabotageEngine }        from './sabotageEngine';
export type { ActivationResult, EffectResolution }                              from './sabotageEngine';
